-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('FOLLOW_REQUEST', 'FOLLOW_ACCEPTED', 'TASK_DUE', 'MILESTONE_DUE', 'REPORT', 'CATEGORY_INVITE', 'CATEGORY_DELETED', 'CATEGORY_ACCEPTED') NOT NULL;
